user:
  url:   /user/:name
  param: { module: user, action: index }

team:
  url:   /team/:name
  param: { module: team, action: index }

activity:
  url:   /activity/:name
  param: { module: activity, action: index }

login:
  url:   /login
  param: { module: login, action: index }

logout:
  url:   /logout
  param: { module: logout, action: index }

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
