group:
  url:   /group/:name
  param: { module: group, action: index }

logout:
  url:   /logout
  param: { module: logout, action: index }

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
