dev:
  propel:
    param:
      classname: DebugPDO
test:
  propel:
    param:
      classname: DebugPDO
all:
  propel:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      dsn: 'mysql:host=chiapei.me;dbname=fantuan'
      username: fantuan
      password: abc123
      encoding: utf8
      persistent: true
      pooling: true
