propel:
  user:
    id:           ~
    email:        { type: varchar(255), required: true, index: unique }
    password:     { type: varchar(255), required: true }
    name:         { type: varchar(255), required: true, index: unique }
    balance:      { type: integer, required: true }
    status:       { type: integer, required: true }
    created_at:   ~

  groups:
    id:           ~
    name:         { type: varchar(255), required: true, index: unique }
    captain:      { type: integer, required: true }
    status:       { type: integer, required: true }
    created_at:   ~

  group_user:
    id:           ~
    group_id:     { type: integer, required: true }
    user_id:      { type: integer, required: true }
    created_at:   ~

  activity:
    id:           ~
    name:         { type: varchar(255), required: true }
    desc:         { type: longvarchar, required: true }
    status:       { type: integer, required: true }
    created_at:   ~

  activity_user:
    id:           ~
    activity_id:  { type: integer, required: true }
    user_id:      { type: integer, required: true }
    cost:         { type: integer, required: true }

  user_charge_history:
    id:           ~
    user_id:      { type: integer, required: true }
    price:        { type: integer, required: true }
    created_at:   ~

  user_consume_history:
    id:           ~
    user_id:      { type: integer, required: true }
    price:        { type: integer, required: true }
    created_at:   ~
